# Generated by Django 5.2.6 on 2025-09-10 14:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenRedefinicaoSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField()),
                ('usado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_redefinicao', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de Redefinição de Senha',
                'verbose_name_plural': 'Tokens de Redefinição de Senha',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
