# Generated by Django 5.2.6 on 2025-09-23 15:29

import core.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tokenredefinicaosenha'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error'), ('CRITICAL', 'Critical')], db_index=True, max_length=10)),
                ('logger', models.CharField(db_index=True, max_length=100)),
                ('message', models.TextField()),
                ('module', models.CharField(blank=True, max_length=100, null=True)),
                ('function', models.CharField(blank=True, max_length=100, null=True)),
                ('line_number', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('action', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('object_id', models.CharField(blank=True, max_length=100, null=True)),
                ('request_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('execution_time', models.FloatField(blank=True, help_text='Tempo de execução em segundos', null=True)),
                ('exception', models.TextField(blank=True, null=True)),
                ('details', models.JSONField(blank=True, help_text='Detalhes adicionais em formato JSON', null=True)),
            ],
            options={
                'verbose_name': 'Entrada de Log',
                'verbose_name_plural': 'Entradas de Log',
                'db_table': 'core_log_entry',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='contrato',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='nota',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='nota',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_inicio',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='data_termino',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Data de Término'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='descricao',
            field=models.TextField(default='', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='empresa',
            field=models.CharField(db_index=True, max_length=200, validators=[core.validators.validate_empresa_name], verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='numero',
            field=models.CharField(db_index=True, default='0000000000', help_text='Formato: XXXX/YYYY', max_length=50, unique=True, validators=[core.validators.validate_contract_number], verbose_name='Número do Contrato'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[core.validators.validate_positive_value], verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='data_entrada',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Data de Entrada'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='data_nota',
            field=models.DateField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='nota',
            name='data_saida',
            field=models.DateField(blank=True, db_index=True, null=True, verbose_name='Data de Saída'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='empenho',
            field=models.CharField(blank=True, db_index=True, help_text='Apenas números, entre 4 e 10 dígitos', max_length=50, null=True, validators=[core.validators.validate_empenho_format], verbose_name='Empenho'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='empresa',
            field=models.CharField(db_index=True, max_length=200, validators=[core.validators.validate_empresa_name], verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='numero',
            field=models.CharField(db_index=True, max_length=50, unique=True, validators=[core.validators.validate_nota_number], verbose_name='Número da Nota'),
        ),
        migrations.AlterField(
            model_name='nota',
            name='setor',
            field=models.CharField(db_index=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='nota',
            name='valor',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=15, validators=[core.validators.validate_positive_value], verbose_name='Valor'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['empresa', 'data_inicio'], name='core_contra_empresa_639c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='contrato',
            index=models.Index(fields=['data_termino', 'alerta_vencimento'], name='core_contra_data_te_4261f4_idx'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['empresa', 'data_entrada'], name='core_nota_empresa_77367c_idx'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['data_saida', 'data_entrada'], name='core_nota_data_sa_d2dcd6_idx'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['contrato', 'data_nota'], name='core_nota_contrat_27f9e3_idx'),
        ),
        migrations.AddIndex(
            model_name='nota',
            index=models.Index(fields=['setor', 'data_entrada'], name='core_nota_setor_3142a8_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['timestamp', 'level'], name='core_log_en_timesta_8214c1_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['user_id', 'timestamp'], name='core_log_en_user_id_77530e_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['action', 'timestamp'], name='core_log_en_action_a395ce_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['ip_address', 'timestamp'], name='core_log_en_ip_addr_cf1049_idx'),
        ),
        migrations.AddIndex(
            model_name='logentry',
            index=models.Index(fields=['logger', 'level', 'timestamp'], name='core_log_en_logger_f5bb8f_idx'),
        ),
    ]
