# Generated by Django 5.2.6 on 2025-09-23 17:56

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_logentry_contrato_created_at_contrato_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='numero',
            field=models.CharField(db_index=True, max_length=50, validators=[core.validators.validate_nota_number], verbose_name='Número da Nota'),
        ),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.UniqueConstraint(fields=('numero', 'empresa'), name='unique_numero_empresa'),
        ),
    ]
