# Generated by Django 5.2.6 on 2025-09-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_nota_numero_nota_unique_numero_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrato',
            name='numero',
            field=models.CharField(db_index=True, default='0000000000', help_text='Número do contrato', max_length=50, unique=True, verbose_name='Número do Contrato'),
        ),
    ]
